# Generated by Django 5.2.11 on 2026-07-13 15:49

import blueflow.models.asset.util
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import netfields.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetCustomFieldName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=126, unique=True)),
                (
                    "display_type",
                    models.TextField(
                        choices=[
                            ("text", "Short text field"),
                            ("textarea", "Multi-line text field"),
                        ],
                        default="text",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
                ("ok_to_scan", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
                ("search_query", models.JSONField(unique=True)),
                ("ok_to_scan", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
                ("color", models.CharField(max_length=7)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ViperWebhookJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("callback", models.CharField()),
                ("since", models.DateTimeField()),
                ("before", models.DateTimeField(blank=True, null=True)),
                ("request_body", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("started", "Started"),
                            ("finished", "Finished"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "system_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blueflow.system",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=126)),
                ("hostname", models.CharField(max_length=256, null=True, unique=True)),
                (
                    "ip_address",
                    netfields.fields.InetAddressField(
                        max_length=39, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "mac_address",
                    netfields.fields.MACAddressField(
                        null=True, unique=True, verbose_name="MAC address"
                    ),
                ),
                (
                    "oui_manufacturer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="NIC vendor",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("model", models.CharField(blank=True, default="", max_length=256)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "udi",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="UDI"
                    ),
                ),
                (
                    "tag_number",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("category", models.CharField(blank=True, default="", max_length=256)),
                ("owner", models.CharField(blank=True, default="", max_length=256)),
                (
                    "os",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Operating System",
                    ),
                ),
                (
                    "app_sw_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Application software version",
                    ),
                ),
                (
                    "last_scanned",
                    models.DateTimeField(
                        default=blueflow.models.asset.util.default_timestamp
                    ),
                ),
                (
                    "last_pinged",
                    models.DateTimeField(
                        default=blueflow.models.asset.util.default_timestamp
                    ),
                ),
                ("external_keys", models.JSONField(blank=True, null=True)),
            ],
            bases=("blueflow.system",),
        ),
        migrations.CreateModel(
            name="ExternalSystem",
            fields=[
                (
                    "system_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blueflow.system",
                    ),
                ),
                (
                    "ip_address",
                    netfields.fields.InetAddressField(
                        max_length=39, null=True, verbose_name="IP address"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=("blueflow.system",),
        ),
        migrations.CreateModel(
            name="HistoricalAsset",
            fields=[
                (
                    "system_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="blueflow.system",
                    ),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=126)),
                (
                    "hostname",
                    models.CharField(db_index=True, max_length=256, null=True),
                ),
                (
                    "ip_address",
                    netfields.fields.InetAddressField(
                        max_length=39, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "mac_address",
                    netfields.fields.MACAddressField(
                        db_index=True, null=True, verbose_name="MAC address"
                    ),
                ),
                (
                    "oui_manufacturer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="NIC vendor",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("model", models.CharField(blank=True, default="", max_length=256)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "udi",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="UDI"
                    ),
                ),
                (
                    "tag_number",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("category", models.CharField(blank=True, default="", max_length=256)),
                ("owner", models.CharField(blank=True, default="", max_length=256)),
                (
                    "os",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Operating System",
                    ),
                ),
                (
                    "app_sw_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Application software version",
                    ),
                ),
                (
                    "last_scanned",
                    models.DateTimeField(
                        default=blueflow.models.asset.util.default_timestamp
                    ),
                ),
                (
                    "last_pinged",
                    models.DateTimeField(
                        default=blueflow.models.asset.util.default_timestamp
                    ),
                ),
                ("external_keys", models.JSONField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asset",
                "verbose_name_plural": "historical assets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTag",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=126)),
                ("color", models.CharField(max_length=7)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tag",
                "verbose_name_plural": "historical tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Cidr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cidr", netfields.fields.CidrAddressField(max_length=43)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueflow.network",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "port",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ]
                    ),
                ),
                ("protocol", models.CharField(max_length=16)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("port", "protocol"), name="unique_port_protocol"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("protocol", ""), _negated=True),
                        name="port_protocol_protocol_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_vulnerabilities", models.IntegerField()),
                ("num_plugins", models.IntegerField()),
                (
                    "provenance",
                    models.TextField(
                        blank=True, help_text="Tool that scanned Asset", null=True
                    ),
                ),
                (
                    "external_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to results page of tool that scanned Asset",
                        null=True,
                    ),
                ),
                ("date_scanned", models.DateTimeField()),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blueflow.asset"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mac_address",
                    netfields.fields.MACAddressField(
                        blank=True, null=True, unique=True
                    ),
                ),
                (
                    "ipv4_address",
                    netfields.fields.InetAddressField(
                        blank=True, max_length=39, null=True, unique=True
                    ),
                ),
                (
                    "ipv6_address",
                    netfields.fields.InetAddressField(
                        blank=True, max_length=39, null=True, unique=True
                    ),
                ),
                (
                    "_asset_match_blacklist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "transmit_ports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=9),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "receive_ports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=9),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("max_confidence", models.SmallIntegerField(default=0)),
                (
                    "_user_asset_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="network_endpoints",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("mac_address", "ipv4_address"),
                    ("mac_address", "ipv6_address"),
                },
            },
        ),
        migrations.CreateModel(
            name="HistoricalAttachment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("file_name", models.TextField()),
                ("file", models.TextField(max_length=100)),
                ("manufacturer", models.TextField(blank=True, null=True)),
                ("model", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical attachment",
                "verbose_name_plural": "historical attachments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAssetTag",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provenance",
                    models.TextField(
                        blank=True,
                        help_text="Reason why tag was added to Asset: automatic, manual, etc.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="blueflow.tag",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asset tag",
                "verbose_name_plural": "historical asset tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAssetCustomField",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="blueflow.assetcustomfieldname",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asset custom field",
                "verbose_name_plural": "historical asset custom fields",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="EndpointSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.SmallIntegerField(default=0)),
                ("confidence_limit", models.SmallIntegerField(default=0)),
                ("evidence", models.JSONField(default=list)),
                (
                    "network_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueflow.networkendpoint",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blueflow.asset"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("file_name", models.TextField()),
                ("file", models.FileField(upload_to="attachments")),
                ("manufacturer", models.TextField(blank=True, null=True)),
                ("model", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueflow.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provenance",
                    models.TextField(
                        blank=True,
                        help_text="Reason why tag was added to Asset: automatic, manual, etc.",
                        null=True,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blueflow.tag"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_tags",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "db_table": "blueflow_asset_tag",
                "unique_together": {("asset", "tag")},
            },
        ),
        migrations.CreateModel(
            name="AssetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provenance",
                    models.TextField(
                        blank=True,
                        help_text="Reason why asset was added to group: automatic, manual, etc.",
                        null=True,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blueflow.group"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_groups",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "db_table": "blueflow_asset_group",
                "unique_together": {("asset", "group")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="groups",
            field=models.ManyToManyField(
                through="blueflow.AssetGroup", to="blueflow.group"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="tags",
            field=models.ManyToManyField(
                through="blueflow.AssetTag", to="blueflow.tag"
            ),
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                    ),
                ),
                ("hour_00", models.IntegerField(default=0)),
                ("hour_01", models.IntegerField(default=0)),
                ("hour_02", models.IntegerField(default=0)),
                ("hour_03", models.IntegerField(default=0)),
                ("hour_04", models.IntegerField(default=0)),
                ("hour_05", models.IntegerField(default=0)),
                ("hour_06", models.IntegerField(default=0)),
                ("hour_07", models.IntegerField(default=0)),
                ("hour_08", models.IntegerField(default=0)),
                ("hour_09", models.IntegerField(default=0)),
                ("hour_10", models.IntegerField(default=0)),
                ("hour_11", models.IntegerField(default=0)),
                ("hour_12", models.IntegerField(default=0)),
                ("hour_13", models.IntegerField(default=0)),
                ("hour_14", models.IntegerField(default=0)),
                ("hour_15", models.IntegerField(default=0)),
                ("hour_16", models.IntegerField(default=0)),
                ("hour_17", models.IntegerField(default=0)),
                ("hour_18", models.IntegerField(default=0)),
                ("hour_19", models.IntegerField(default=0)),
                ("hour_20", models.IntegerField(default=0)),
                ("hour_21", models.IntegerField(default=0)),
                ("hour_22", models.IntegerField(default=0)),
                ("hour_23", models.IntegerField(default=0)),
                ("last_window_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "day_of_week"),
                        name="usage_unique_per_asset_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetPortProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "port_protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueflow.portprotocol",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_protocols",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "port_protocol"),
                        name="unique_asset_port_protocol",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueflow.assetcustomfieldname",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_custom_fields",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "field")},
            },
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hostname__isnull", True),
                    models.Q(("hostname", ""), _negated=True),
                    _connector="OR",
                ),
                name="asset_hostname_not_empty_when_set",
            ),
        ),
    ]
