# Generated by Django 5.2.11 on 2026-07-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="mac_address",
        ),
        migrations.RemoveField(
            model_name="historicalasset",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="historicalasset",
            name="mac_address",
        ),
    ]
