# Generated by Django 5.2.11 on 2026-07-17 16:46

import django.db.models.deletion
import django_extensions.db.fields
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0002_remove_asset_ip_address_remove_asset_mac_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "mac_address",
                    netfields.fields.MACAddressField(
                        null=True, unique=True, verbose_name="MAC address"
                    ),
                ),
                (
                    "ipv4",
                    netfields.fields.InetAddressField(
                        max_length=39, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "ipv6",
                    netfields.fields.InetAddressField(
                        max_length=39, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interface",
                        to="blueflow.system",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
