# Generated by Django 5.2.11 on 2026-03-11 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueflow', '0002_remove_alert_connector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViperWebhookJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('callback', models.URLField()),
                ('since', models.DateTimeField()),
                ('before', models.DateTimeField(blank=True, null=True)),
                ('request_body', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('finished', 'Finished'), ('error', 'Error')], default='pending', max_length=16)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
