# Generated by Django 5.2.11 on 2026-07-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0003_networkinterface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkinterface",
            name="system",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interface",
                to="blueflow.system",
            ),
        ),
    ]
