# Generated by Django 5.2.11 on 2026-05-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0003_viperwebhookjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="pulsefeeditem",
        ),
        migrations.RemoveField(
            model_name="vulnerability",
            name="pulse_feed_item",
        ),
        migrations.DeleteModel(
            name="HistoricalPulseFeedItem",
        ),
        migrations.DeleteModel(
            name="PulseFeedItem",
        ),
    ]
