# Generated by Django 5.2.11 on 2026-07-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0004_alter_networkinterface_system"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cidr",
            name="network",
        ),
        migrations.RemoveField(
            model_name="endpointsuggestion",
            name="asset",
        ),
        migrations.RemoveField(
            model_name="endpointsuggestion",
            name="network_endpoint",
        ),
        migrations.AlterUniqueTogether(
            name="networkendpoint",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="networkendpoint",
            name="_user_asset_match",
        ),
        migrations.DeleteModel(
            name="SavedSearch",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="asset",
        ),
        migrations.DeleteModel(
            name="Cidr",
        ),
        migrations.DeleteModel(
            name="Network",
        ),
        migrations.DeleteModel(
            name="EndpointSuggestion",
        ),
        migrations.DeleteModel(
            name="NetworkEndpoint",
        ),
        migrations.DeleteModel(
            name="Scan",
        ),
    ]
