# Generated by Django 5.2.11 on 2026-07-22 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blueflow",
            "0005_remove_cidr_network_remove_endpointsuggestion_asset_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "port",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ]
                    ),
                ),
                ("protocol", models.CharField(max_length=16)),
                (
                    "cast_type",
                    models.CharField(
                        choices=[
                            ("unicast", "Unicast"),
                            ("multicast", "Multicast"),
                            ("broadcast", "Broadcast"),
                        ],
                        default="unicast",
                    ),
                ),
                ("response_seen", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("port", "protocol"), name="unique_request_port_protocol"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("protocol", ""), _negated=True),
                        name="request_protocol_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.BooleanField(default=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="blueflow.asset",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueflow.request",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AssetPortProtocol",
        ),
        migrations.DeleteModel(
            name="PortProtocol",
        ),
        migrations.AddConstraint(
            model_name="assetrequest",
            constraint=models.UniqueConstraint(
                fields=("asset", "request"), name="unique_asset_request"
            ),
        ),
    ]
