# Generated by Django 5.2.11 on 2026-07-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0006_request_assetrequest_delete_assetportprotocol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="service",
            field=models.CharField(blank=True, default=""),
        ),
    ]
