# Generated by Django 5.2.11 on 2026-05-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0006_asset_open_ports_tcp_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                    ),
                ),
                ("hour_00", models.IntegerField(default=0)),
                ("hour_01", models.IntegerField(default=0)),
                ("hour_02", models.IntegerField(default=0)),
                ("hour_03", models.IntegerField(default=0)),
                ("hour_04", models.IntegerField(default=0)),
                ("hour_05", models.IntegerField(default=0)),
                ("hour_06", models.IntegerField(default=0)),
                ("hour_07", models.IntegerField(default=0)),
                ("hour_08", models.IntegerField(default=0)),
                ("hour_09", models.IntegerField(default=0)),
                ("hour_10", models.IntegerField(default=0)),
                ("hour_11", models.IntegerField(default=0)),
                ("hour_12", models.IntegerField(default=0)),
                ("hour_13", models.IntegerField(default=0)),
                ("hour_14", models.IntegerField(default=0)),
                ("hour_15", models.IntegerField(default=0)),
                ("hour_16", models.IntegerField(default=0)),
                ("hour_17", models.IntegerField(default=0)),
                ("hour_18", models.IntegerField(default=0)),
                ("hour_19", models.IntegerField(default=0)),
                ("hour_20", models.IntegerField(default=0)),
                ("hour_21", models.IntegerField(default=0)),
                ("hour_22", models.IntegerField(default=0)),
                ("hour_23", models.IntegerField(default=0)),
                ("last_window_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="blueflow.asset",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asset", "day_of_week"),
                        name="usage_unique_per_asset_per_day",
                    )
                ],
            },
        ),
    ]
