# Generated by Django 5.2.11 on 2026-07-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0007_request_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalsystem",
            name="hostname",
            field=models.CharField(null=True, unique=True),
        ),
    ]
