# Generated by Django 5.2.11 on 2026-05-19 21:23

import blueflow.models.asset
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0007_usage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="risk_score",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="risk_score_cli",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="risk_score_impact",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="risk_score_likelihood",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="risk_score_pri",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="risk_score_remediable",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="risk_score_sec",
        ),
        migrations.RemoveField(
            model_name="historicalasset",
            name="risk_score",
        ),
        migrations.RemoveField(
            model_name="historicalasset",
            name="risk_score_cli",
        ),
        migrations.RemoveField(
            model_name="historicalasset",
            name="risk_score_impact",
        ),
        migrations.RemoveField(
            model_name="historicalasset",
            name="risk_score_likelihood",
        ),
        migrations.RemoveField(
            model_name="historicalasset",
            name="risk_score_pri",
        ),
        migrations.RemoveField(
            model_name="historicalasset",
            name="risk_score_remediable",
        ),
        migrations.RemoveField(
            model_name="historicalasset",
            name="risk_score_sec",
        ),
        migrations.AlterField(
            model_name="asset",
            name="open_ports_tcp",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                default=list,
                size=None,
                validators=[blueflow.models.asset.validate_tcp_port_range],
                verbose_name="Open TCP ports",
            ),
        ),
        migrations.AlterField(
            model_name="historicalasset",
            name="open_ports_tcp",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                default=list,
                size=None,
                validators=[blueflow.models.asset.validate_tcp_port_range],
                verbose_name="Open TCP ports",
            ),
        ),
    ]
