# Generated by Django 5.2.11 on 2026-07-28 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0008_externalsystem_hostname"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_receivers",
                        to="blueflow.system",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_requests",
                        to="blueflow.request",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_senders",
                        to="blueflow.system",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AssetRequest",
        ),
        migrations.AddConstraint(
            model_name="systemrequest",
            constraint=models.UniqueConstraint(
                fields=("sender", "receiver", "request"),
                name="unique_sender_receiver_request",
            ),
        ),
    ]
