# Generated by Django 5.2.11 on 2026-07-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0008_externalsystem_hostname"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assetrequest",
            name="unique_asset_request",
        ),
    ]
