# Generated by Django 5.2.11 on 2026-07-28 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0009_systemrequest_delete_assetrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemrequest",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_receivers",
                to="blueflow.system",
            ),
        ),
    ]
