# Generated by Django 5.2.11 on 2026-07-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0009_remove_assetrequest_unique_asset_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.BooleanField(default=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_requests",
                        to="blueflow.request",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="blueflow.system",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AssetRequest",
        ),
    ]
