# Generated by Django 5.2.11 on 2026-07-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0010_alter_systemrequest_receiver"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="request",
            name="unique_request_port_protocol",
        ),
    ]
