# Generated by Django 5.2.11 on 2026-05-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0010_asset_time_aware_finalize"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="model",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="historicalasset",
            old_name="model",
            new_name="product",
        ),
    ]
