# Generated by Django 5.2.11 on 2026-08-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0011_remove_request_unique_request_port_protocol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalsystem",
            name="ip_address",
        ),
    ]
