# Generated by Django 5.2.11 on 2026-05-28 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0011_rename_model_asset_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="product",
            new_name="model",
        ),
        migrations.RenameField(
            model_name="historicalasset",
            old_name="product",
            new_name="model",
        ),
    ]
