# Generated by Django 5.2.11 on 2026-06-15 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0012_rename_product_asset_model_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "port",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ]
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("TCP", "Tcp"), ("UDP", "Udp")], default="TCP"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("port", "protocol"), name="unique_port_protocol"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetPortProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_protocols",
                        to="blueflow.asset",
                    ),
                ),
                (
                    "port_protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blueflow.portprotocol",
                    ),
                ),
            ],
        ),
    ]
