# Generated by Django 5.2.11 on 2026-06-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blueflow", "0013_portprotocol_assetportprotocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portprotocol",
            name="protocol",
            field=models.CharField(
                choices=[("tcp", "Tcp"), ("udp", "Udp")], default="tcp"
            ),
        ),
    ]
