# Generated by Django 5.2.10 on 2026-02-12 20:23

import collections
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="A submodule of the connectors module.",
                        max_length=126,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "celery_task_name",
                    models.TextField(
                        help_text="Full function as str. E.g., connectors.sleep.__main__.main"
                    ),
                ),
                ("settings", models.JSONField(default=collections.OrderedDict)),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ConnectorTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("celery_task_id", models.CharField(max_length=36, unique=True)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=collections.OrderedDict)),
                ("attachment", models.FileField(null=True, upload_to="tmp_scan")),
                ("status", models.CharField(blank=True, max_length=126, null=True)),
                ("progress_total", models.IntegerField(default=1000)),
                ("progress_count", models.IntegerField(default=0)),
                ("stdout", models.TextField(blank=True, default="")),
                ("stdout_count", models.IntegerField(default=0)),
                ("stderr", models.TextField(blank=True, default="")),
                ("stderr_count", models.IntegerField(default=0)),
                ("retval", models.TextField(blank=True, null=True)),
                ("periodic", models.BooleanField(default=False)),
                (
                    "external_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to the 'results' of this particular connection",
                        null=True,
                    ),
                ),
                (
                    "date_submitted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_started", models.DateTimeField(null=True)),
                ("date_finished", models.DateTimeField(null=True)),
                (
                    "connector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="connectors.connector",
                    ),
                ),
            ],
        ),
    ]
