# Generated by Django 5.2.11 on 2026-02-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bf_opencore", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="connector",
        ),
        migrations.RemoveField(
            model_name="connectortask",
            name="connector",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="scans",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="connectortask",
        ),
        migrations.AlterUniqueTogether(
            name="scan",
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name="Connector",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="connector_task",
        ),
        migrations.DeleteModel(
            name="ConnectorTask",
        ),
    ]
