# Generated by Django 5.2.11 on 2026-03-11 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf_opencore", "0002_remove_alert_connector_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViperWebhookJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("callback", models.URLField()),
                ("since", models.DateTimeField()),
                ("before", models.DateTimeField(blank=True, null=True)),
                ("request_body", models.JSONField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
