# Generated by Django 5.2.11 on 2026-03-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf_opencore", "0003_add_viperwebhookjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="viperwebhookjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("finished", "Finished"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
