# Generated by Django 5.2.10 on 2026-02-04 19:31

import collections
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import netfields.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=126, null=True)),
                ("hostname", models.TextField(blank=True, null=True)),
                (
                    "ip_address",
                    netfields.fields.InetAddressField(
                        blank=True, max_length=39, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "mac_address",
                    netfields.fields.MACAddressField(
                        blank=True, null=True, unique=True, verbose_name="MAC address"
                    ),
                ),
                (
                    "nic_vendor",
                    models.TextField(blank=True, null=True, verbose_name="NIC vendor"),
                ),
                ("manufacturer", models.TextField(blank=True, null=True)),
                ("model", models.TextField(blank=True, null=True)),
                ("serial_number", models.TextField(blank=True, null=True)),
                ("udi", models.TextField(blank=True, null=True, verbose_name="UDI")),
                ("tag_number", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                (
                    "risk_score_cli",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Safety risk score"
                    ),
                ),
                (
                    "risk_score_sec",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Security risk score"
                    ),
                ),
                (
                    "risk_score_pri",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Privacy risk score"
                    ),
                ),
                (
                    "risk_score_likelihood",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Likelihood risk score"
                    ),
                ),
                (
                    "risk_score_impact",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Impact risk score"
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("owner", models.TextField(blank=True, null=True)),
                (
                    "os",
                    models.TextField(
                        blank=True, null=True, verbose_name="Operating System"
                    ),
                ),
                (
                    "app_sw_version",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Application software version",
                    ),
                ),
                ("last_scanned", models.DateTimeField(blank=True, null=True)),
                ("last_pinged", models.DateTimeField(blank=True, null=True)),
                (
                    "open_ports_tcp",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        default=list,
                        size=None,
                        verbose_name="Open TCP ports",
                    ),
                ),
                ("external_keys", models.JSONField(blank=True, null=True)),
                ("risk_score_remediable", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="AssetCustomFieldName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=126, unique=True)),
                (
                    "display_type",
                    models.TextField(
                        choices=[
                            ("text", "Short text field"),
                            ("textarea", "Multi-line text field"),
                        ],
                        default="text",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="A submodule of the connectors module.",
                        max_length=126,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "celery_task_name",
                    models.TextField(
                        help_text="Full function as str. E.g., connectors.sleep.__main__.main"
                    ),
                ),
                ("settings", models.JSONField(default=collections.OrderedDict)),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
                ("ok_to_scan", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="PulseFeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_pulse_id", models.IntegerField(editable=False, unique=True)),
                ("date_last_updated", models.DateTimeField(editable=False)),
                ("title", models.TextField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in-progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "affected_manufs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        editable=False,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "affected_models",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        editable=False,
                        null=True,
                        size=None,
                    ),
                ),
                ("json", models.JSONField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
                ("search_query", models.JSONField(unique=True)),
                ("ok_to_scan", models.BooleanField(default=False)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
                ("color", models.CharField(max_length=7)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="AssetCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_custom_fields",
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.assetcustomfieldname",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "field")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="custom_fields",
            field=models.ManyToManyField(
                through="bf_opencore.AssetCustomField",
                to="bf_opencore.assetcustomfieldname",
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("file_name", models.TextField()),
                ("file", models.FileField(upload_to="attachments")),
                ("manufacturer", models.TextField(blank=True, null=True)),
                ("model", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConnectorTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("celery_task_id", models.CharField(max_length=36, unique=True)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=collections.OrderedDict)),
                ("attachment", models.FileField(null=True, upload_to="tmp_scan")),
                ("status", models.CharField(blank=True, max_length=126, null=True)),
                ("progress_total", models.IntegerField(default=1000)),
                ("progress_count", models.IntegerField(default=0)),
                ("stdout", models.TextField(blank=True, default="")),
                ("stdout_count", models.IntegerField(default=0)),
                ("stderr", models.TextField(blank=True, default="")),
                ("stderr_count", models.IntegerField(default=0)),
                ("retval", models.TextField(blank=True, null=True)),
                ("periodic", models.BooleanField(default=False)),
                (
                    "external_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to the 'results' of this particular connection",
                        null=True,
                    ),
                ),
                (
                    "date_submitted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_started", models.DateTimeField(null=True)),
                ("date_finished", models.DateTimeField(null=True)),
                (
                    "connector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bf_opencore.connector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provenance",
                    models.TextField(
                        blank=True,
                        help_text="Reason why asset was added to group: automatic, manual, etc.",
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_groups",
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.group",
                    ),
                ),
            ],
            options={
                "db_table": "blueflow_asset_group",
                "unique_together": {("asset", "group")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="groups",
            field=models.ManyToManyField(
                through="bf_opencore.AssetGroup", to="bf_opencore.group"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAsset",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=126, null=True)),
                ("hostname", models.TextField(blank=True, null=True)),
                (
                    "ip_address",
                    netfields.fields.InetAddressField(
                        blank=True, max_length=39, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "mac_address",
                    netfields.fields.MACAddressField(
                        blank=True, db_index=True, null=True, verbose_name="MAC address"
                    ),
                ),
                (
                    "nic_vendor",
                    models.TextField(blank=True, null=True, verbose_name="NIC vendor"),
                ),
                ("manufacturer", models.TextField(blank=True, null=True)),
                ("model", models.TextField(blank=True, null=True)),
                ("serial_number", models.TextField(blank=True, null=True)),
                ("udi", models.TextField(blank=True, null=True, verbose_name="UDI")),
                ("tag_number", models.TextField(blank=True, null=True)),
                ("category", models.TextField(blank=True, null=True)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                (
                    "risk_score_cli",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Safety risk score"
                    ),
                ),
                (
                    "risk_score_sec",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Security risk score"
                    ),
                ),
                (
                    "risk_score_pri",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Privacy risk score"
                    ),
                ),
                (
                    "risk_score_likelihood",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Likelihood risk score"
                    ),
                ),
                (
                    "risk_score_impact",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Impact risk score"
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("owner", models.TextField(blank=True, null=True)),
                (
                    "os",
                    models.TextField(
                        blank=True, null=True, verbose_name="Operating System"
                    ),
                ),
                (
                    "app_sw_version",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Application software version",
                    ),
                ),
                ("last_scanned", models.DateTimeField(blank=True, null=True)),
                ("last_pinged", models.DateTimeField(blank=True, null=True)),
                (
                    "open_ports_tcp",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        default=list,
                        size=None,
                        verbose_name="Open TCP ports",
                    ),
                ),
                ("external_keys", models.JSONField(blank=True, null=True)),
                ("risk_score_remediable", models.FloatField(default=0.0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asset",
                "verbose_name_plural": "historical assets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAssetCustomField",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf_opencore.assetcustomfieldname",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asset custom field",
                "verbose_name_plural": "historical asset custom fields",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAttachment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("file_name", models.TextField()),
                ("file", models.TextField(max_length=100)),
                ("manufacturer", models.TextField(blank=True, null=True)),
                ("model", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical attachment",
                "verbose_name_plural": "historical attachments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPulseFeedItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "external_pulse_id",
                    models.IntegerField(db_index=True, editable=False),
                ),
                ("date_last_updated", models.DateTimeField(editable=False)),
                ("title", models.TextField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in-progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "affected_manufs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        editable=False,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "affected_models",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        editable=False,
                        null=True,
                        size=None,
                    ),
                ),
                ("json", models.JSONField(blank=True, editable=False, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pulse feed item",
                "verbose_name_plural": "historical pulse feed items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTag",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=126)),
                ("color", models.CharField(max_length=7)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tag",
                "verbose_name_plural": "historical tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Cidr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cidr", netfields.fields.CidrAddressField(max_length=43)),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.network",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mac_address",
                    netfields.fields.MACAddressField(
                        blank=True, null=True, unique=True
                    ),
                ),
                (
                    "ipv4_address",
                    netfields.fields.InetAddressField(
                        blank=True, max_length=39, null=True, unique=True
                    ),
                ),
                (
                    "ipv6_address",
                    netfields.fields.InetAddressField(
                        blank=True, max_length=39, null=True, unique=True
                    ),
                ),
                (
                    "_asset_match_blacklist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "transmit_ports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=9),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "receive_ports",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=9),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("max_confidence", models.SmallIntegerField(default=0)),
                (
                    "_user_asset_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="network_endpoints",
                        to="bf_opencore.asset",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("mac_address", "ipv4_address"),
                    ("mac_address", "ipv6_address"),
                },
            },
        ),
        migrations.CreateModel(
            name="EndpointSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.SmallIntegerField(default=0)),
                ("confidence_limit", models.SmallIntegerField(default=0)),
                ("evidence", models.JSONField(default=list)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "network_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.networkendpoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_vulnerabilities", models.IntegerField()),
                ("num_plugins", models.IntegerField()),
                (
                    "provenance",
                    models.TextField(
                        blank=True, help_text="Tool that scanned Asset", null=True
                    ),
                ),
                (
                    "external_url",
                    models.TextField(
                        blank=True,
                        help_text="URL to results page of tool that scanned Asset",
                        null=True,
                    ),
                ),
                ("date_scanned", models.DateTimeField()),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "connector_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.connectortask",
                    ),
                ),
            ],
            options={
                "unique_together": {("asset", "connector_task")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="scans",
            field=models.ManyToManyField(
                through="bf_opencore.Scan", to="bf_opencore.connectortask"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAssetTag",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provenance",
                    models.TextField(
                        blank=True,
                        help_text="Reason why tag was added to Asset: automatic, manual, etc.",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bf_opencore.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical asset tag",
                "verbose_name_plural": "historical asset tags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AssetTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "provenance",
                    models.TextField(
                        blank=True,
                        help_text="Reason why tag was added to Asset: automatic, manual, etc.",
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_tags",
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.tag",
                    ),
                ),
            ],
            options={
                "db_table": "blueflow_asset_tag",
                "unique_together": {("asset", "tag")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="tags",
            field=models.ManyToManyField(
                through="bf_opencore.AssetTag", to="bf_opencore.tag"
            ),
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="unique name, e.g., 'Nessus 10001'",
                        max_length=126,
                        unique=True,
                    ),
                ),
                ("solution", models.TextField(blank=True, null=True)),
                ("synopsis", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "external_page_url",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "cves",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True, null=True),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "pulse_feed_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vulnerabilities",
                        to="bf_opencore.pulsefeeditem",
                        to_field="external_pulse_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetVulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_remediated", models.DateTimeField(null=True)),
                ("date_ignored", models.DateTimeField(null=True)),
                (
                    "provenance",
                    models.TextField(
                        blank=True,
                        help_text="Tool that added Vulnerability to Asset, e.g., 'Nessus'.",
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_vulnerabilities",
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bf_opencore.vulnerability",
                    ),
                ),
            ],
            options={
                "db_table": "blueflow_asset_vulnerability",
                "unique_together": {("asset", "vulnerability")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="vulnerabilities",
            field=models.ManyToManyField(
                through="bf_opencore.AssetVulnerability", to="bf_opencore.vulnerability"
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("external_page_url", models.URLField(null=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_read", models.DateTimeField(null=True)),
                ("date_expiration", models.DateTimeField(null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_assets",
                        to="bf_opencore.asset",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_connectors",
                        to="bf_opencore.connector",
                    ),
                ),
                (
                    "connectortask",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_connector_tasks",
                        to="bf_opencore.connectortask",
                    ),
                ),
                (
                    "pulsefeeditem",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_pulsefeeditems",
                        to="bf_opencore.pulsefeeditem",
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_vulnerabilities",
                        to="bf_opencore.vulnerability",
                    ),
                ),
            ],
        ),
    ]
