# Generated by Django 5.2.10 on 2026-02-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf_opencore", "0001_initial"),
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectortask",
            name="connector",
        ),
        migrations.AlterField(
            model_name="alert",
            name="connector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alert_connectors",
                to="connectors.connector",
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="connector_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="connectors.connectortask",
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="connectortask",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alert_connector_tasks",
                to="connectors.connectortask",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="scans",
            field=models.ManyToManyField(
                through="bf_opencore.Scan", to="connectors.connectortask"
            ),
        ),
        migrations.DeleteModel(
            name="Connector",
        ),
        migrations.DeleteModel(
            name="ConnectorTask",
        ),
    ]
